apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: routereflectors.route-reflector.ibm.com
spec:
  group: route-reflector.ibm.com
  names:
    kind: RouteReflector
    listKind: RouteReflectorList
    plural: routereflectors
    singular: routereflector
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: RouteReflector is the Schema for the routereflectors API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        ignoredPools:
          items:
            type: string
          type: array
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        preferredPool:
          type: string
        spec:
          description: RouteReflectorSpec defines the desired state of RouteReflector
          type: object
        status:
          description: RouteReflectorStatus defines the observed state of RouteReflector
          properties:
            routeReflectors:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                type: string
              type: array
          required:
          - routeReflectors
          type: object
      required:
      - ignoredPools
      - preferredPool
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
